[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
message = { path="../crate_message" }
log = "0.4.20"
simple_logger = "4.2.0"
clap = { version = "4.4.8", features = ['derive']}
anyhow = "1.0.75"
